
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    default_type  application/octet-stream;
    include       /mime.types;

    # Simple json log format
    log_format json escape=json '{ "@timestamp":"$time_iso8601", "remote_addr":"$remote_addr", "remote_user":"$remote_user", "request_method":"$request_method", "scheme":"$scheme", "host":"$host", "request_uri":"$request_uri", "server_protocol":"$server_protocol", "status":"$status", "body_bytes_sent":"$body_bytes_sent", "request_time":"$request_time", "upstream_addr":"$upstream_addr", "upstream_response_time":"$upstream_response_time", "http_referer":"$http_referer", "http_user_agent":"$http_user_agent" }';

    access_log  logs/access.log  json;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            proxy_pass http://symfexit:8000;
            proxy_set_header Host "localhost:8002";
        }

        location /static/ {
            alias /staticfiles/;
        }

        location /theme/ {
            alias /content/theme/;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

}
